"""add  to workflows

Revision ID: 5f6291109057
Revises: 4e99a8df00ff
Create Date: 2024-06-14 06:30:41.326661

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '5f6291109057'
down_revision = '4e99a8df00ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_variables', sa.Text(), nullable=True))
    op.execute("UPDATE workflows SET global_variables = '{}' WHERE global_variables IS NULL")
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('global_variables', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('global_variables')

    # ### end Alembic commands ###
