name: dify

x-shared-env: &shared-api-worker-env
  # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  # Debug mode, default is false. It is recommended to turn on this configuration for local development to prevent some problems caused by monkey patch.
  DEBUG: ${DEBUG:-false}
  # Flask debug mode, it can output trace information at the interface when turned on, which is convenient for debugging.
  FLASK_DEBUG: ${FLASK_DEBUG:-false}
  # A secretkey that is used for securely signing the session cookie and encrypting sensitive information on the database. You can generate a strong key using `openssl rand -base64 42`.
  SECRET_KEY: ${SECRET_KEY}
  # Password for admin user initialization.
  # If left unset, admin user will not be prompted for a password when creating the initial admin account.
  INIT_PASSWORD: ${INIT_PASSWORD}
  # The base URL of console application web frontend, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_WEB_URL: ${CONSOLE_WEB_URL}
  # The base URL of console application api server, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_API_URL: ${CONSOLE_API_URL}
  # The URL prefix for Service API endpoints, refers to the base URL of the current API service if api domain is
  # different from console domain.
  # example: http://api.dify.ai
  SERVICE_API_URL: ${SERVICE_API_URL}
  # The URL prefix for Web APP frontend, refers to the Web App base URL of WEB service if web app domain is different from
  # console or api domain.
  # example: http://udify.app
  APP_WEB_URL: ${APP_WEB_URL}
  # Whether to enable the version check policy. If set to false, https://updates.dify.ai will not be called for version check.
  CHECK_UPDATE_URL: ${CHECK_UPDATE_URL}
  # Used to change the OpenAI base address, default is https://api.openai.com/v1.
  # When OpenAI cannot be accessed in China, replace it with a domestic mirror address,
  # or when a local model provides OpenAI compatible API, it can be replaced.
  OPENAI_API_BASE: ${OPENAI_API_BASE}
  # File preview or download Url prefix.
  # used to display File preview or download Url to the front-end or as Multi-model inputs;
  # Url is signed and has expiration time.
  FILES_URL: ${FILES_URL}
  # File Access Time specifies a time interval in seconds for the file to be accessed.
  # The default value is 300 seconds.
  FILES_ACCESS_TIMEOUT: ${FILES_ACCESS_TIMEOUT:-300}
  # When enabled, migrations will be executed prior to application startup and the application will start after the migrations have completed.
  MIGRATION_ENABLED: ${MIGRATION_ENABLED:-true}
  # Deployment environment.
  # Supported values are `PRODUCTION`, `TESTING`. Default is `PRODUCTION`.
  # Testing environment. There will be a distinct color label on the front-end page,
  # indicating that this environment is a testing environment.
  DEPLOY_ENV: ${DEPLOY_ENV:-PRODUCTION}
  # API service binding address, default: 0.0.0.0, i.e., all addresses can be accessed.
  DIFY_BIND_ADDRESS: ${DIFY_BIND_ADDRESS}
  # API service binding port number, default 5001.
  DIFY_PORT: ${DIFY_PORT}
  # The number of API server workers, i.e., the number of gevent workers.
  # Formula: number of cpu cores x 2 + 1
  # Reference: https://docs.gunicorn.org/en/stable/design.html#how-many-workers
  SERVER_WORKER_AMOUNT: ${SERVER_WORKER_AMOUNT}
  # Defaults to gevent. If using windows, it can be switched to sync or solo.
  SERVER_WORKER_CLASS: ${SERVER_WORKER_CLASS}
  # Similar to SERVER_WORKER_CLASS. Default is gevent.
  # If using windows, it can be switched to sync or solo.
  CELERY_WORKER_CLASS: ${CELERY_WORKER_CLASS}
  # Request handling timeout. The default is 200,
  # it is recommended to set it to 360 to support a longer sse connection time.
  GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT}
  # The number of Celery workers. The default is 1, and can be set as needed.
  CELERY_WORKER_AMOUNT: ${CELERY_WORKER_AMOUNT}
  # The configurations of postgres database connection.
  # It is consistent with the configuration in the 'db' service below.
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_DATABASE: ${DB_DATABASE}
  # The size of the database connection pool.
  # The default is 30 connections, which can be appropriately increased.
  SQLALCHEMY_POOL_SIZE: ${SQLALCHEMY_POOL_SIZE}
  # Database connection pool recycling time, the default is 3600 seconds.
  SQLALCHEMY_POOL_RECYCLE: ${SQLALCHEMY_POOL_RECYCLE}
  # Whether to print SQL, default is false.
  SQLALCHEMY_ECHO: ${SQLALCHEMY_ECHO}
  # The configurations of redis connection.
  # It is consistent with the configuration in the 'redis' service below.
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT:-6379}
  REDIS_USERNAME: ${REDIS_USERNAME}
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_USE_SSL: ${REDIS_USE_SSL}
  # Redis Database, default is 0. Please use a different Database from Session Redis and Celery Broker.
  REDIS_DB: 0
  # The configurations of celery broker.
  # Use redis as the broker, and redis db 1 for celery broker.
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  BROKER_USE_SSL: ${BROKER_USE_SSL}
  # Specifies the allowed origins for cross-origin requests to the Web API, e.g. https://dify.app or * for all origins.
  WEB_API_CORS_ALLOW_ORIGINS: ${WEB_API_CORS_ALLOW_ORIGINS}
  # Specifies the allowed origins for cross-origin requests to the console API, e.g. https://cloud.dify.ai or * for all origins.
  CONSOLE_CORS_ALLOW_ORIGINS: ${CONSOLE_CORS_ALLOW_ORIGINS}
  # The type of storage to use for storing user files. Supported values are `local` and `s3` and `azure-blob` and `google-storage`, Default: `local`
  STORAGE_TYPE: ${STORAGE_TYPE}
  # The path to the local storage directory, the directory relative the root path of API service codes or absolute path. Default: `storage` or `/home/john/storage`.
  # only available when STORAGE_TYPE is `local`.
  STORAGE_LOCAL_PATH: storage
  # The S3 storage configurations, only available when STORAGE_TYPE is `s3`.
  S3_USE_AWS_MANAGED_IAM: ${S3_USE_AWS_MANAGED_IAM}
  S3_ENDPOINT: ${S3_ENDPOINT}
  S3_BUCKET_NAME: ${S3_BUCKET_NAME}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}
  S3_REGION: ${S3_REGION}
  # The Azure Blob storage configurations, only available when STORAGE_TYPE is `azure-blob`.
  AZURE_BLOB_ACCOUNT_NAME: ${AZURE_BLOB_ACCOUNT_NAME}
  AZURE_BLOB_ACCOUNT_KEY: ${AZURE_BLOB_ACCOUNT_KEY}
  AZURE_BLOB_CONTAINER_NAME: ${AZURE_BLOB_CONTAINER_NAME}
  AZURE_BLOB_ACCOUNT_URL: ${AZURE_BLOB_ACCOUNT_URL}
  # The Google storage configurations, only available when STORAGE_TYPE is `google-storage`.
  GOOGLE_STORAGE_BUCKET_NAME: ${GOOGLE_STORAGE_BUCKET_NAME}
  # if you want to use Application Default Credentials, you can leave GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64 empty.
  GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64: ${GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64}
  # The Alibaba Cloud OSS configurations, only available when STORAGE_TYPE is `aliyun-oss`
  ALIYUN_OSS_BUCKET_NAME: ${ALIYUN_OSS_BUCKET_NAME}
  ALIYUN_OSS_ACCESS_KEY: ${ALIYUN_OSS_ACCESS_KEY}
  ALIYUN_OSS_SECRET_KEY: ${ALIYUN_OSS_SECRET_KEY}
  ALIYUN_OSS_ENDPOINT: ${ALIYUN_OSS_ENDPOINT}
  ALIYUN_OSS_REGION: ${ALIYUN_OSS_REGION}
  ALIYUN_OSS_AUTH_VERSION: ${ALIYUN_OSS_AUTH_VERSION}
  # The Tencent COS storage configurations, only available when STORAGE_TYPE is `tencent-cos`.
  TENCENT_COS_BUCKET_NAME: ${TENCENT_COS_BUCKET_NAME}
  TENCENT_COS_SECRET_KEY: ${TENCENT_COS_SECRET_KEY}
  TENCENT_COS_SECRET_ID: ${TENCENT_COS_SECRET_ID}
  TENCENT_COS_REGION: ${TENCENT_COS_REGION}
  TENCENT_COS_SCHEME: ${TENCENT_COS_SCHEME}
  # The type of vector store to use. Supported values are `weaviate`, `qdrant`, `milvus`, `relyt`, `pgvector`, `chroma`, 'opensearch', 'tidb_vector'.
  VECTOR_STORE: ${VECTOR_STORE}
  # The Weaviate endpoint URL. Only available when VECTOR_STORE is `weaviate`.
  WEAVIATE_ENDPOINT: ${WEAVIATE_ENDPOINT}
  # The Weaviate API key.
  WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}
  # The Qdrant endpoint URL. Only available when VECTOR_STORE is `qdrant`.
  QDRANT_URL: ${QDRANT_URL}
  # The Qdrant API key.
  QDRANT_API_KEY: ${QDRANT_API_KEY}
  # The Qdrant client timeout setting.
  QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT}
  # The Qdrant client enable gRPC mode.
  QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED}
  # The Qdrant server gRPC mode PORT.
  QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
  # Milvus configuration Only available when VECTOR_STORE is `milvus`.
  # The milvus host.
  MILVUS_HOST: ${MILVUS_HOST}
  # The milvus host.
  MILVUS_PORT: ${MILVUS_PORT}
  # The milvus username.
  MILVUS_USER: ${MILVUS_USER}
  # The milvus password.
  MILVUS_PASSWORD: ${MILVUS_PASSWORD}
  # The milvus tls switch.
  MILVUS_SECURE: ${MILVUS_SECURE}
  # relyt configurations
  RELYT_HOST: ${RELYT_HOST}
  RELYT_PORT: ${RELYT_PORT}
  RELYT_USER: ${RELYT_USER}
  RELYT_PASSWORD: ${RELYT_PASSWORD}
  RELYT_DATABASE: ${RELYT_DATABASE}
  # pgvector configurations
  PGVECTOR_HOST: ${PGVECTOR_HOST}
  PGVECTOR_PORT: ${PGVECTOR_PORT}
  PGVECTOR_USER: ${PGVECTOR_USER}
  PGVECTOR_PASSWORD: ${PGVECTOR_PASSWORD}
  PGVECTOR_DATABASE: ${PGVECTOR_DATABASE}
  # tidb vector configurations
  TIDB_VECTOR_HOST: ${TIDB_VECTOR_HOST}
  TIDB_VECTOR_PORT: ${TIDB_VECTOR_PORT}
  TIDB_VECTOR_USER: ${TIDB_VECTOR_USER}
  TIDB_VECTOR_PASSWORD: ${TIDB_VECTOR_PASSWORD}
  TIDB_VECTOR_DATABASE: ${TIDB_VECTOR_DATABASE}
  # oracle configurations
  ORACLE_HOST: ${ORACLE_HOST}
  ORACLE_PORT: ${ORACLE_PORT}
  ORACLE_USER: ${ORACLE_USER}
  ORACLE_PASSWORD: ${ORACLE_PASSWORD}
  ORACLE_DATABASE: ${ORACLE_DATABASE}
  # Chroma configuration
  CHROMA_HOST: ${CHROMA_HOST}
  CHROMA_PORT: ${CHROMA_PORT}
  CHROMA_TENANT: ${CHROMA_TENANT}
  CHROMA_DATABASE: ${CHROMA_DATABASE}
  CHROMA_AUTH_PROVIDER: ${CHROMA_AUTH_PROVIDER}
  CHROMA_AUTH_CREDENTIALS: ${CHROMA_AUTH_CREDENTIALS}
  # OpenSearch configuration
  OPENSEARCH_HOST: ${OPENSEARCH_HOST}
  OPENSEARCH_PORT: ${OPENSEARCH_PORT}
  OPENSEARCH_USER: ${OPENSEARCH_USER}
  OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
  OPENSEARCH_SECURE: ${OPENSEARCH_SECURE}
  # tencent configurations
  TENCENT_VECTOR_DB_URL: ${TENCENT_VECTOR_DB_URL}
  TENCENT_VECTOR_DB_API_KEY: ${TENCENT_VECTOR_DB_API_KEY}
  TENCENT_VECTOR_DB_TIMEOUT: ${TENCENT_VECTOR_DB_TIMEOUT}
  TENCENT_VECTOR_DB_USERNAME: ${TENCENT_VECTOR_DB_USERNAME}
  TENCENT_VECTOR_DB_DATABASE: ${TENCENT_VECTOR_DB_DATABASE}
  TENCENT_VECTOR_DB_SHARD: ${TENCENT_VECTOR_DB_SHARD}
  TENCENT_VECTOR_DB_REPLICAS: ${TENCENT_VECTOR_DB_REPLICAS}
  # Knowledge Configuration
  # Upload file size limit, default 15M.
  UPLOAD_FILE_SIZE_LIMIT: ${UPLOAD_FILE_SIZE_LIMIT}
  # The maximum number of files that can be uploaded at a time, default 5.
  UPLOAD_FILE_BATCH_LIMIT: ${UPLOAD_FILE_BATCH_LIMIT}
  # `dify` Dify's proprietary file extraction scheme
  # `Unstructured` Unstructured.io file extraction scheme
  ETL_TYPE: ${ETL_TYPE}
  # Unstructured API path, needs to be configured when ETL_TYPE is Unstructured.
  UNSTRUCTURED_API_URL: ${UNSTRUCTURED_API_URL}
  # Multi-modal Configuration
  # The format of the image sent when the multi-modal model is input, the default is base64, optional url.
  MULTIMODAL_SEND_IMAGE_FORMAT: ${MULTIMODAL_SEND_IMAGE_FORMAT}
  # Upload image file size limit, default 10M.
  UPLOAD_IMAGE_FILE_SIZE_LIMIT: ${UPLOAD_IMAGE_FILE_SIZE_LIMIT}
  # The DSN for Sentry error reporting. If not set, Sentry error reporting will be disabled.
  SENTRY_DSN: ${SENTRY_DSN}
  # The sample rate for Sentry events. Default: `1.0`
  SENTRY_TRACES_SAMPLE_RATE: ${SENTRY_TRACES_SAMPLE_RATE}
  # The sample rate for Sentry profiles. Default: `1.0`
  SENTRY_PROFILES_SAMPLE_RATE: ${SENTRY_PROFILES_SAMPLE_RATE}
  # Notion import configuration, support public and internal
  NOTION_INTEGRATION_TYPE: ${NOTION_INTEGRATION_TYPE}
  NOTION_CLIENT_SECRET: ${NOTION_CLIENT_SECRET}
  NOTION_CLIENT_ID: ${NOTION_CLIENT_ID}
  NOTION_INTERNAL_SECRET: ${NOTION_INTERNAL_SECRET}
  # Mail configuration, support: resend, smtp
  MAIL_TYPE: ${MAIL_TYPE}
  # default send from email address, if not specified
  MAIL_DEFAULT_SEND_FROM: ${MAIL_DEFAULT_SEND_FROM}
  SMTP_SERVER: ${SMTP_SERVER}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_USERNAME: ${SMTP_USERNAME}
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  SMTP_USE_TLS: ${SMTP_USE_TLS}
  SMTP_OPPORTUNISTIC_TLS: ${SMTP_OPPORTUNISTIC_TLS}
  # the api-key for resend (https://resend.com)
  RESEND_API_KEY: ${RESEND_API_KEY}
  RESEND_API_URL: https://api.resend.com
  # Indexing configuration
  INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: ${INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH}
  # Other configurations
  INVITE_EXPIRY_HOURS: ${INVITE_EXPIRY_HOURS}
  CODE_EXECUTION_ENDPOINT: ${CODE_EXECUTION_ENDPOINT:-http://sandbox:8194}
  CODE_EXECUTION_API_KEY: ${CODE_EXECUTION_API_KEY:-dify-sandbox}
  CODE_MAX_NUMBER: ${CODE_MAX_NUMBER:-9223372036854775807}
  CODE_MIN_NUMBER: ${CODE_MIN_NUMBER:- -9223372036854775808}
  CODE_MAX_STRING_LENGTH: ${CODE_MAX_STRING_LENGTH:-80000}
  TEMPLATE_TRANSFORM_MAX_LENGTH: ${TEMPLATE_TRANSFORM_MAX_LENGTH:-80000}
  CODE_MAX_STRING_ARRAY_LENGTH: ${CODE_MAX_STRING_ARRAY_LENGTH:-30}
  CODE_MAX_OBJECT_ARRAY_LENGTH: ${CODE_MAX_OBJECT_ARRAY_LENGTH:-30}
  CODE_MAX_NUMBER_ARRAY_LENGTH: ${CODE_MAX_NUMBER_ARRAY_LENGTH:-1000}
  SSRF_PROXY_HTTP_URL: ${SSRF_PROXY_HTTP_URL:-'http://ssrf_proxy:3128'}
  SSRF_PROXY_HTTPS_URL: ${SSRF_PROXY_HTTPS_URL:-'http://ssrf_proxy:3128'}

services:
  api:
    image: dify-python-nonroot-${USERID:?set this like USERID=$$(id -u)}
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - userid=${USERID}
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      # Startup mode, 'api' starts the API server.
      MODE: api
    networks:
      - ssrf_proxy_network
      - default
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/home/developer/app
    working_dir: /home/developer/app
    command: bash -l -c "_venv/bin/poetry run flask run --host 0.0.0.0 --port=5001 --debug"

networks:
  default:
    external: true
    name: dify_middleware
  ssrf_proxy_network:
    external: true
    name: dify_ssrf_proxy_network
